repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: [ pyyaml ]

      # - id: cmake-lint

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
