# generate doxygen

name: Docs
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Setup Python
            uses: actions/setup-python@v3
            with:
              python-version: 3.12

          - name: Clone submodules
            run: |
              python pull-submodules.py --clean --dontask

          - name: Install dependencies
            run: |
              apt-get update
              apt-get install -y doxygen

          - name: Build doxygen
            run: |
              cd doc/doxygen
              doxygen REST.conf

          - name: Upload docs
            uses: actions/upload-artifact@v3
            with:
              name: docs
              path: doc/doxygen
              retention-days: 1
